export const ENG_TO_HEB_TEAM_NAME_MAP: { [key: string]: string } = {
    'Maccabi Tel-Aviv': 'מכבי תל אביב',
    'Hapoel Jerusalem': 'הפועל ירושלים',
    'M. Rishon': 'מכבי ראשון לציון',
    'Ness Ziona': 'עירוני נס ציונה',
    'Hapoel Galil Elion': 'הפועל גליל עליון',
    'Hapoel Haemek': 'הפועל העמק',
    'Beer Sheva/Dimona': 'הפועל באר שבע',
    'Hapoel Tel-Aviv': 'הפועל תל אביב',
    'Ironi Kiryat Ata': 'עירוני קרית אתא',
    'M. Ra;ananna': 'מכבי רעננה',
    'Elitzur Netanya': 'אליצור עירוני נתניה',
    'Hapoel Holon': 'הפועל חולון',
    'Maccabi Ramat Gan': 'מכבי רמת גן',
    'Hapoel IBI Tel Aviv': 'הפועל תל אביב',



    'Valencia Basket': 'ולנסיה',
    'FC Barcelona': 'ברצלונה',
    'Fenerbahce Beko Istanbul': 'פנרבחצ\'ה',
    'AS Monaco': 'מונאקו',
    'Zalgiris Kaunas': 'ז\'לגיריס קובנה',
    'Crvena Zvezda Meridianbet Belgrade': 'הכוכב האדום בלגרס',
    'Panathinaikos AKTOR Athens': 'פנאתינייקוס',
    'Real Madrid': 'ריאל מדריד',
    'Olympiacos Piraeus': 'אולימפיאקוס',
    'EA7 Emporio Armani Milan': 'מילאנו',
    'Dubai Basketball': 'דובאי',
    'Virtus Bologna': 'וירטוס בולוניה',
    'Partizan Mozzart Bet Belgrade': 'פרטיזן בלגרד',
    'Paris Basketball': 'פריז בסקטבול',
    'Maccabi Rapyd Tel Aviv': 'מכבי תל אביב',
    'Kosner Baskonia Vitoria-Gasteiz': 'בסקוניה',
    'Anadolu Efes Istanbul': 'אנאדולו אפס',
    'FC Bayern Munich': 'באיירן מינכן',
    'LDLC ASVEL Villeurbanne': 'ליון-וילרבן'
}