export const ENG_TO_HEB_PLAYER_NAME_MAP: { [key: string]: string } = {
    'Iffe Lundberg': 'איפה לונדברג',
    'Jaylen Hoard': 'ג\'יילן הורד',
    'Jimmy Clark Iii': 'ג\'ימי קלארק',
    'Marcio Santos': 'מרסיו סנטוס',
    'Lonnie Walker Iv': 'לוני ווקר',
    'Roman Sorking': 'רומן סורקין',
    'O Shae J Brissett': 'אושיי בריסט',
    'William Rayman': 'ויל ריימן',
    'John Dibartolomeo': 'ג\'ון דיברתולומיאו',
    'Tj Leaf': 'טי.ג\'יי ליף',
    'Zachary Hankins': 'זאק הנקינס',
    'Tamir Blatt': 'תמיר בלאט',

    'Brancou Badio': 'ברנקו באדיו',
    'Kameron Taylor': 'קמרון טיילור',
    'Josep Puerto': 'ז\'וזפ פוארטו',
    'Nathan Reuvers': 'ניית׳ן רוברס',
    'Jaime Pradilla': 'חיימה פראדיה',
    'Sergio De Larrea': 'סרחיו דה לאראה',
    'Braxton Key': 'ברקסטון קי',
    'Jean Montero': 'ז\'אן מונטרו',
    'Omari Moore': 'עומארי מור',
    'Darius Thompson': 'דריוס תומפסון',
    'Matthew Costello': 'מאט קוסטלו',
    'Yankuba Sima': 'יאנקובה סימה'
}